// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_error.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Msg {

  /// <summary>Holder for reflection information generated from msg_error.proto</summary>
  public static partial class MsgErrorReflection {

    #region Descriptor
    /// <summary>File descriptor for msg_error.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MsgErrorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9tc2dfZXJyb3IucHJvdG8SA21zZyoqCghlcnJfdHlwZRIMCghlcnJfbm9u",
            "ZRAAEhAKC2Vycl91bmtub3duEJBOYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Msg.err_type), }, null));
    }
    #endregion

  }
  #region Enums
  public enum err_type {
    /// <summary>
    /// 성공
    /// </summary>
    [pbr::OriginalName("err_none")] ErrNone = 0,
    /// <summary>
    /// 알수없는 에러.(예외처리)
    /// </summary>
    [pbr::OriginalName("err_unknown")] ErrUnknown = 10000,
  }

  #endregion

}

#endregion Designer generated code
