// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_enum.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Msg {

  /// <summary>Holder for reflection information generated from msg_enum.proto</summary>
  public static partial class MsgEnumReflection {

    #region Descriptor
    /// <summary>File descriptor for msg_enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MsgEnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5tc2dfZW51bS5wcm90bxIDbXNnKjkKDXBsYXRmb3JtX3R5cGUSCAoEbm9u",
            "ZRAAEgkKBWd1ZXN0EAESCgoGZGlyZWN0EAISBwoDdG95EANiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Msg.platform_type), }, null));
    }
    #endregion

  }
  #region Enums
  public enum platform_type {
    [pbr::OriginalName("none")] None = 0,
    [pbr::OriginalName("guest")] Guest = 1,
    [pbr::OriginalName("direct")] Direct = 2,
    [pbr::OriginalName("toy")] Toy = 3,
  }

  #endregion

}

#endregion Designer generated code
