# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg_type_api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg_type_api.proto',
  package='msg',
  syntax='proto3',
  serialized_pb=_b('\n\x12msg_type_api.proto\x12\x03msg*\xfc\x01\n\x08type_api\x12\x08\n\x04none\x10\x00\x12\x10\n\x0bt_login_req\x10\xddV\x12\x10\n\x0bt_login_ack\x10\xdeV\x12\x18\n\x13t_get_char_list_req\x10\xc1W\x12\x18\n\x13t_get_char_list_ack\x10\xc2W\x12\x16\n\x11t_create_char_req\x10\xc3W\x12\x16\n\x11t_create_char_ack\x10\xc4W\x12\x16\n\x11t_delete_char_req\x10\xc5W\x12\x16\n\x11t_delete_char_ack\x10\xc6W\x12\x16\n\x11t_select_char_req\x10\xc7W\x12\x16\n\x11t_select_char_ack\x10\xc8Wb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_TYPE_API = _descriptor.EnumDescriptor(
  name='type_api',
  full_name='msg.type_api',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='none', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='t_login_req', index=1, number=11101,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='t_login_ack', index=2, number=11102,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='t_get_char_list_req', index=3, number=11201,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='t_get_char_list_ack', index=4, number=11202,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='t_create_char_req', index=5, number=11203,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='t_create_char_ack', index=6, number=11204,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='t_delete_char_req', index=7, number=11205,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='t_delete_char_ack', index=8, number=11206,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='t_select_char_req', index=9, number=11207,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='t_select_char_ack', index=10, number=11208,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=28,
  serialized_end=280,
)
_sym_db.RegisterEnumDescriptor(_TYPE_API)

type_api = enum_type_wrapper.EnumTypeWrapper(_TYPE_API)
none = 0
t_login_req = 11101
t_login_ack = 11102
t_get_char_list_req = 11201
t_get_char_list_ack = 11202
t_create_char_req = 11203
t_create_char_ack = 11204
t_delete_char_req = 11205
t_delete_char_ack = 11206
t_select_char_req = 11207
t_select_char_ack = 11208


DESCRIPTOR.enum_types_by_name['type_api'] = _TYPE_API


# @@protoc_insertion_point(module_scope)
