# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg_error.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg_error.proto',
  package='msg',
  syntax='proto3',
  serialized_pb=_b('\n\x0fmsg_error.proto\x12\x03msg**\n\x08\x65rr_type\x12\x0c\n\x08\x65rr_none\x10\x00\x12\x10\n\x0b\x65rr_unknown\x10\x90Nb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_ERR_TYPE = _descriptor.EnumDescriptor(
  name='err_type',
  full_name='msg.err_type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='err_none', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='err_unknown', index=1, number=10000,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=24,
  serialized_end=66,
)
_sym_db.RegisterEnumDescriptor(_ERR_TYPE)

err_type = enum_type_wrapper.EnumTypeWrapper(_ERR_TYPE)
err_none = 0
err_unknown = 10000


DESCRIPTOR.enum_types_by_name['err_type'] = _ERR_TYPE


# @@protoc_insertion_point(module_scope)
