# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg_enum.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg_enum.proto',
  package='msg',
  syntax='proto3',
  serialized_pb=_b('\n\x0emsg_enum.proto\x12\x03msg*9\n\rplatform_type\x12\x08\n\x04none\x10\x00\x12\t\n\x05guest\x10\x01\x12\n\n\x06\x64irect\x10\x02\x12\x07\n\x03toy\x10\x03\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_PLATFORM_TYPE = _descriptor.EnumDescriptor(
  name='platform_type',
  full_name='msg.platform_type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='none', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='guest', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='direct', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='toy', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=23,
  serialized_end=80,
)
_sym_db.RegisterEnumDescriptor(_PLATFORM_TYPE)

platform_type = enum_type_wrapper.EnumTypeWrapper(_PLATFORM_TYPE)
none = 0
guest = 1
direct = 2
toy = 3


DESCRIPTOR.enum_types_by_name['platform_type'] = _PLATFORM_TYPE


# @@protoc_insertion_point(module_scope)
